---
- hosts: localhost
  connection: local
  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "key"
      # vpc_subnet_id: 
      instance_type: t2.micro
      security_group: default
      region: ap-south-1
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_access_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - { image: "ami-0c50b6f7dc3701ddd", name: "manage-node-1" } # Amazon Linux
      - { image: "ami-00bb6a80f01f03502", name: "manage-node-2" } # Ubuntu 20.04 LTS
      - { image: "ami-00bb6a80f01f03502", name: "manage-node-3" } # Ubuntu 20.04 LTS