---
# tasks file for ec2
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "ansible-instance"
    # key_name: "key"
    # vpc_subnet_id: subnet-083ae9b35fb0d5748
    instance_type: "{{ type }}"
    security_group: default
    region: ap-south-1
    state: terminated
    aws_access_key: "{{aws_access_key}}"  # From vault as defined
    aws_secret_key: "{{aws_secret_key}}"  # From vault as defined      
    network:
      assign_public_ip: true
    image_id: ami-0c50b6f7dc3701ddd
    tags:
      Environment: Testing
